# Generated by Django 2.2.6 on 2021-11-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assignmentsolution_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classEndTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='classStartTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
